/* 
*  Copyright (c) 2018 Georgia-Pacific.  All rights reserved.
*  This software is the confidential and proprietary information of Georgia-Pacific.
*/

package com.gpintegration.quples;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "CMMConsumer", targetNamespace = "http://www.sap.com/CMMConsumer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMMConsumer {


    /**
     *
     * @param contactRequest
     * @return
     *     returns java.util.List<com.gpintegration.quples.ContactsResponse>
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.sap.com/CMMConsumer/NewOperation")
    @WebResult(name = "ContactResponse", targetNamespace = "")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.sap.com/CMMConsumer/", className = "com.gpintegration.quples.NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.sap.com/CMMConsumer/", className = "com.gpintegration.quples.NewOperationResponse")
	List<ContactsResponse> newOperation(
        @WebParam(name = "ContactRequest", targetNamespace = "")
        List<Contacts> contactRequest);

}
