/*
*  Copyright (c) 2018 Georgia-Pacific.  All rights reserved.
*  This software is the confidential and proprietary information of Georgia-Pacific.
*/

package com.gpintegration.quples;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.apache.log4j.Logger;

import de.hybris.platform.util.Config;
import de.hybris.platform.util.Utilities;
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CMMConsumer", targetNamespace = "http://www.sap.com/CMMConsumer/")
public class CMMConsumer_Service
    extends Service
{
	private static final Logger LOG = Logger.getLogger(CMMConsumer_Service.class);
    private final static URL CMMCONSUMER_WSDL_LOCATION;
    private final static WebServiceException CMMCONSUMER_EXCEPTION;
    private final static QName CMMCONSUMER_QNAME = new QName("http://www.sap.com/CMMConsumer/", "CMMConsumer");
    private final static String WSDL_PATH_NAME="qples.wsdl.name";
    private static final String PROJECT_ROOT_PATH = Utilities.getExtensionInfo("gpintegration").getExtensionDirectory().getAbsolutePath();
    private static final String DEFAULT_WSDL = "/resources/gpintegration/wsdl/CMMConsumerNew.wsdl";
    private static final String QPLS_USER_NAME = "qples.user.name";
    private static final String QPLS_PASSWORD = "qples.user.password";
    private static final String FILE_PATH = PROJECT_ROOT_PATH + Config.getString(WSDL_PATH_NAME, DEFAULT_WSDL);

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:"+FILE_PATH);
            LOG.debug(" WSDL PATH " + url.toString());
        } catch (MalformedURLException ex) {
        	LOG.error("error in CMMConsumer_service"+ex.getMessage());
            e = new WebServiceException(ex);
        }
        CMMCONSUMER_WSDL_LOCATION = url;
        CMMCONSUMER_EXCEPTION = e;
    }

    public CMMConsumer_Service() {
        super(__getWsdlLocation(), CMMCONSUMER_QNAME);
    }

    public CMMConsumer_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMMCONSUMER_QNAME, features);
    }

    public CMMConsumer_Service(URL wsdlLocation) {
        super(wsdlLocation, CMMCONSUMER_QNAME);
    }

    public CMMConsumer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMMCONSUMER_QNAME, features);
    }

    public CMMConsumer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMMConsumer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMMConsumer
     */
    @WebEndpoint(name = "CMMConsumerSOAP")
    public CMMConsumer getCMMConsumerSOAP() {
    	CMMConsumer services= super.getPort(new QName("http://www.sap.com/CMMConsumer/", "CMMConsumerSOAP"), CMMConsumer.class);
	// Add username and password for Basic Authentication
	Map<String, Object> reqContext = ((BindingProvider) services).getRequestContext();
	reqContext.put(BindingProvider.USERNAME_PROPERTY, Config.getParameter(QPLS_USER_NAME));
	reqContext.put(BindingProvider.PASSWORD_PROPERTY, Config.getParameter(QPLS_PASSWORD));
	/*******************************************************************/
    	return services;
    }


    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMMConsumer
     */
    @WebEndpoint(name = "CMMConsumerSOAP")
    public CMMConsumer getCMMConsumerSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sap.com/CMMConsumer/", "CMMConsumerSOAP"), CMMConsumer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMMCONSUMER_EXCEPTION!= null) {
            throw CMMCONSUMER_EXCEPTION;
        }
        return CMMCONSUMER_WSDL_LOCATION;
    }
    


}
