/* 
*  Copyright (c) 2018 Georgia-Pacific.  All rights reserved.
*  This software is the confidential and proprietary information of Georgia-Pacific.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 12:50:44 AM IST 
//


package com.gp.businessobjects.service.addr.suggestions.input;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the addr.cleanse.suggestions.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CITY2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "CITY2");
    private final static QName _CITY1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "CITY1");
    private final static QName _STRSUPPL3_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "STR_SUPPL3");
    private final static QName _STRSUPPL2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "STR_SUPPL2");
    private final static QName _STRSUPPL1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "STR_SUPPL1");
    private final static QName _REPLY1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "REPLY1");
    private final static QName _POBOXCTY_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "PO_BOX_CTY");
    private final static QName _HOUSENUM1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "HOUSE_NUM1");
    private final static QName _HOUSENUM2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "HOUSE_NUM2");
    private final static QName _POBOX_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "PO_BOX");
    private final static QName _REGION_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "REGION");
    private final static QName _POBOXREG_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "PO_BOX_REG");
    private final static QName _ROOMNUMBER_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "ROOMNUMBER");
    private final static QName _STREET_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "STREET");
    private final static QName _POSTCODE1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "POST_CODE1");
    private final static QName _COUNTRY_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "COUNTRY");
    private final static QName _BUILDING_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "BUILDING");
    private final static QName _POSTCODE2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "POST_CODE2");
    private final static QName _FLOOR_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "FLOOR");
    private final static QName _NATION_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "NATION");
    private final static QName _POBOXNUM_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "PO_BOX_NUM");
    private final static QName _HOMECITY_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "HOME_CITY");
    private final static QName _LOCATION_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "LOCATION");
    private final static QName _TABLEOFFSET_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "TABLE_OFFSET");
    private final static QName _POBOXLOC_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", "PO_BOX_LOC");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: addr.cleanse.suggestions.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSet }
     * 
     */
    public DataSet createDataSet() {
        return new DataSet();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "CITY2")
    public JAXBElement<String> createCITY2(String value) {
        return new JAXBElement<String>(_CITY2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "CITY1")
    public JAXBElement<String> createCITY1(String value) {
        return new JAXBElement<String>(_CITY1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "STR_SUPPL3")
    public JAXBElement<String> createSTRSUPPL3(String value) {
        return new JAXBElement<String>(_STRSUPPL3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "STR_SUPPL2")
    public JAXBElement<String> createSTRSUPPL2(String value) {
        return new JAXBElement<String>(_STRSUPPL2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "STR_SUPPL1")
    public JAXBElement<String> createSTRSUPPL1(String value) {
        return new JAXBElement<String>(_STRSUPPL1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "REPLY1")
    public JAXBElement<String> createREPLY1(String value) {
        return new JAXBElement<String>(_REPLY1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "PO_BOX_CTY")
    public JAXBElement<String> createPOBOXCTY(String value) {
        return new JAXBElement<String>(_POBOXCTY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "HOUSE_NUM1")
    public JAXBElement<String> createHOUSENUM1(String value) {
        return new JAXBElement<String>(_HOUSENUM1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "HOUSE_NUM2")
    public JAXBElement<String> createHOUSENUM2(String value) {
        return new JAXBElement<String>(_HOUSENUM2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "PO_BOX")
    public JAXBElement<String> createPOBOX(String value) {
        return new JAXBElement<String>(_POBOX_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "REGION")
    public JAXBElement<String> createREGION(String value) {
        return new JAXBElement<String>(_REGION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "PO_BOX_REG")
    public JAXBElement<String> createPOBOXREG(String value) {
        return new JAXBElement<String>(_POBOXREG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "ROOMNUMBER")
    public JAXBElement<String> createROOMNUMBER(String value) {
        return new JAXBElement<String>(_ROOMNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "STREET")
    public JAXBElement<String> createSTREET(String value) {
        return new JAXBElement<String>(_STREET_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "POST_CODE1")
    public JAXBElement<String> createPOSTCODE1(String value) {
        return new JAXBElement<String>(_POSTCODE1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "COUNTRY")
    public JAXBElement<String> createCOUNTRY(String value) {
        return new JAXBElement<String>(_COUNTRY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "BUILDING")
    public JAXBElement<String> createBUILDING(String value) {
        return new JAXBElement<String>(_BUILDING_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "POST_CODE2")
    public JAXBElement<String> createPOSTCODE2(String value) {
        return new JAXBElement<String>(_POSTCODE2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "FLOOR")
    public JAXBElement<String> createFLOOR(String value) {
        return new JAXBElement<String>(_FLOOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "NATION")
    public JAXBElement<String> createNATION(String value) {
        return new JAXBElement<String>(_NATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "PO_BOX_NUM")
    public JAXBElement<String> createPOBOXNUM(String value) {
        return new JAXBElement<String>(_POBOXNUM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "HOME_CITY")
    public JAXBElement<String> createHOMECITY(String value) {
        return new JAXBElement<String>(_HOMECITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "LOCATION")
    public JAXBElement<String> createLOCATION(String value) {
        return new JAXBElement<String>(_LOCATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "TABLE_OFFSET")
    public JAXBElement<String> createTABLEOFFSET(String value) {
        return new JAXBElement<String>(_TABLEOFFSET_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/input", name = "PO_BOX_LOC")
    public JAXBElement<String> createPOBOXLOC(String value) {
        return new JAXBElement<String>(_POBOXLOC_QNAME, String.class, null, value);
    }

}
