/* 
*  Copyright (c) 2018 Georgia-Pacific.  All rights reserved.
*  This software is the confidential and proprietary information of Georgia-Pacific.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 12:51:38 AM IST 
//


package com.gp.businessobjects.service.addr.suggestions.output;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the addr.cleanse.suggestions.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _POSTCODE2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "POST_CODE2");
    private final static QName _PRIMARYSIDEI_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "PRIMARY_SIDE_I");
    private final static QName _SUGGFULLLASTLN_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SUGG_FULL_LASTLN");
    private final static QName _BUILDING_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "BUILDING");
    private final static QName _COUNTRY_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "COUNTRY");
    private final static QName _POSTCODE1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "POST_CODE1");
    private final static QName _FLOOR_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "FLOOR");
    private final static QName _HOMECITY_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "HOME_CITY");
    private final static QName _ASGMTTYPE_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "ASGMT_TYPE");
    private final static QName _SUGGFULLADDRLN_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SUGG_FULL_ADDRLN");
    private final static QName _REGION2LONG_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "REGION2_LONG");
    private final static QName _STATUSCODEPO_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "STATUS_CODE_PO");
    private final static QName _TABLEOFFSET_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "TABLE_OFFSET");
    private final static QName _POBOXLOC_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "PO_BOX_LOC");
    private final static QName _LOCATION_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "LOCATION");
    private final static QName _SUGGERROR_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SUGG_ERROR");
    private final static QName _SUGGSINGLEADDR_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SUGG_SINGLE_ADDR");
    private final static QName _SUGGSTATUS_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SUGG_STATUS");
    private final static QName _INFOCODEPO_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "INFO_CODE_PO");
    private final static QName _REGION2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "REGION2");
    private final static QName _CITY1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "CITY1");
    private final static QName _CITY2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "CITY2");
    private final static QName _SECONDARYSIDEI_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SECONDARY_SIDE_I");
    private final static QName _POBOXREG2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "PO_BOX_REG2");
    private final static QName _STRSUPPL1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "STR_SUPPL1");
    private final static QName _STRSUPPL2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "STR_SUPPL2");
    private final static QName _SELECTION_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SELECTION");
    private final static QName _STRSUPPL3_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "STR_SUPPL3");
    private final static QName _SUGGCOUNT_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "SUGG_COUNT");
    private final static QName _POBOXCTY_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "PO_BOX_CTY");
    private final static QName _ASGMTTYPEPO_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "ASGMT_TYPE_PO");
    private final static QName _HOUSENUM2_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "HOUSE_NUM2");
    private final static QName _HOUSENUM1_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "HOUSE_NUM1");
    private final static QName _POBOX_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "PO_BOX");
    private final static QName _INFOCODE_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "INFO_CODE");
    private final static QName _REGION_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "REGION");
    private final static QName _POBOXREG_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "PO_BOX_REG");
    private final static QName _POBOXLOBBY_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "PO_BOX_LOBBY");
    private final static QName _ASGMTLEVEL_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "ASGMT_LEVEL");
    private final static QName _ASGMTLEVELPO_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "ASGMT_LEVEL_PO");
    private final static QName _STATUSCODE_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "STATUS_CODE");
    private final static QName _STREET_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "STREET");
    private final static QName _ROOMNUMBER_QNAME = new QName("http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", "ROOMNUMBER");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: addr.cleanse.suggestions.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSet }
     * 
     */
    public DataSet createDataSet() {
        return new DataSet();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link SUGGESTION }
     * 
     */
    public SUGGESTION createSUGGESTION() {
        return new SUGGESTION();
    }

    /**
     * Create an instance of {@link ENTRY }
     * 
     */
    public ENTRY createENTRY() {
        return new ENTRY();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "POST_CODE2")
    public JAXBElement<String> createPOSTCODE2(String value) {
        return new JAXBElement<String>(_POSTCODE2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "PRIMARY_SIDE_I")
    public JAXBElement<String> createPRIMARYSIDEI(String value) {
        return new JAXBElement<String>(_PRIMARYSIDEI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SUGG_FULL_LASTLN")
    public JAXBElement<String> createSUGGFULLLASTLN(String value) {
        return new JAXBElement<String>(_SUGGFULLLASTLN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "BUILDING")
    public JAXBElement<String> createBUILDING(String value) {
        return new JAXBElement<String>(_BUILDING_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "COUNTRY")
    public JAXBElement<String> createCOUNTRY(String value) {
        return new JAXBElement<String>(_COUNTRY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "POST_CODE1")
    public JAXBElement<String> createPOSTCODE1(String value) {
        return new JAXBElement<String>(_POSTCODE1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "FLOOR")
    public JAXBElement<String> createFLOOR(String value) {
        return new JAXBElement<String>(_FLOOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "HOME_CITY")
    public JAXBElement<String> createHOMECITY(String value) {
        return new JAXBElement<String>(_HOMECITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "ASGMT_TYPE")
    public JAXBElement<String> createASGMTTYPE(String value) {
        return new JAXBElement<String>(_ASGMTTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SUGG_FULL_ADDRLN")
    public JAXBElement<String> createSUGGFULLADDRLN(String value) {
        return new JAXBElement<String>(_SUGGFULLADDRLN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "REGION2_LONG")
    public JAXBElement<String> createREGION2LONG(String value) {
        return new JAXBElement<String>(_REGION2LONG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "STATUS_CODE_PO")
    public JAXBElement<String> createSTATUSCODEPO(String value) {
        return new JAXBElement<String>(_STATUSCODEPO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "TABLE_OFFSET")
    public JAXBElement<String> createTABLEOFFSET(String value) {
        return new JAXBElement<String>(_TABLEOFFSET_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "PO_BOX_LOC")
    public JAXBElement<String> createPOBOXLOC(String value) {
        return new JAXBElement<String>(_POBOXLOC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "LOCATION")
    public JAXBElement<String> createLOCATION(String value) {
        return new JAXBElement<String>(_LOCATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SUGG_ERROR")
    public JAXBElement<String> createSUGGERROR(String value) {
        return new JAXBElement<String>(_SUGGERROR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SUGG_SINGLE_ADDR")
    public JAXBElement<String> createSUGGSINGLEADDR(String value) {
        return new JAXBElement<String>(_SUGGSINGLEADDR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SUGG_STATUS")
    public JAXBElement<String> createSUGGSTATUS(String value) {
        return new JAXBElement<String>(_SUGGSTATUS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "INFO_CODE_PO")
    public JAXBElement<String> createINFOCODEPO(String value) {
        return new JAXBElement<String>(_INFOCODEPO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "REGION2")
    public JAXBElement<String> createREGION2(String value) {
        return new JAXBElement<String>(_REGION2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "CITY1")
    public JAXBElement<String> createCITY1(String value) {
        return new JAXBElement<String>(_CITY1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "CITY2")
    public JAXBElement<String> createCITY2(String value) {
        return new JAXBElement<String>(_CITY2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SECONDARY_SIDE_I")
    public JAXBElement<String> createSECONDARYSIDEI(String value) {
        return new JAXBElement<String>(_SECONDARYSIDEI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "PO_BOX_REG2")
    public JAXBElement<String> createPOBOXREG2(String value) {
        return new JAXBElement<String>(_POBOXREG2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "STR_SUPPL1")
    public JAXBElement<String> createSTRSUPPL1(String value) {
        return new JAXBElement<String>(_STRSUPPL1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "STR_SUPPL2")
    public JAXBElement<String> createSTRSUPPL2(String value) {
        return new JAXBElement<String>(_STRSUPPL2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SELECTION")
    public JAXBElement<String> createSELECTION(String value) {
        return new JAXBElement<String>(_SELECTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "STR_SUPPL3")
    public JAXBElement<String> createSTRSUPPL3(String value) {
        return new JAXBElement<String>(_STRSUPPL3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "SUGG_COUNT")
    public JAXBElement<BigInteger> createSUGGCOUNT(BigInteger value) {
        return new JAXBElement<BigInteger>(_SUGGCOUNT_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "PO_BOX_CTY")
    public JAXBElement<String> createPOBOXCTY(String value) {
        return new JAXBElement<String>(_POBOXCTY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "ASGMT_TYPE_PO")
    public JAXBElement<String> createASGMTTYPEPO(String value) {
        return new JAXBElement<String>(_ASGMTTYPEPO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "HOUSE_NUM2")
    public JAXBElement<String> createHOUSENUM2(String value) {
        return new JAXBElement<String>(_HOUSENUM2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "HOUSE_NUM1")
    public JAXBElement<String> createHOUSENUM1(String value) {
        return new JAXBElement<String>(_HOUSENUM1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "PO_BOX")
    public JAXBElement<String> createPOBOX(String value) {
        return new JAXBElement<String>(_POBOX_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "INFO_CODE")
    public JAXBElement<String> createINFOCODE(String value) {
        return new JAXBElement<String>(_INFOCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "REGION")
    public JAXBElement<String> createREGION(String value) {
        return new JAXBElement<String>(_REGION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "PO_BOX_REG")
    public JAXBElement<String> createPOBOXREG(String value) {
        return new JAXBElement<String>(_POBOXREG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "PO_BOX_LOBBY")
    public JAXBElement<String> createPOBOXLOBBY(String value) {
        return new JAXBElement<String>(_POBOXLOBBY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "ASGMT_LEVEL")
    public JAXBElement<String> createASGMTLEVEL(String value) {
        return new JAXBElement<String>(_ASGMTLEVEL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "ASGMT_LEVEL_PO")
    public JAXBElement<String> createASGMTLEVELPO(String value) {
        return new JAXBElement<String>(_ASGMTLEVELPO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "STATUS_CODE")
    public JAXBElement<String> createSTATUSCODE(String value) {
        return new JAXBElement<String>(_STATUSCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "STREET")
    public JAXBElement<String> createSTREET(String value) {
        return new JAXBElement<String>(_STREET_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", name = "ROOMNUMBER")
    public JAXBElement<String> createROOMNUMBER(String value) {
        return new JAXBElement<String>(_ROOMNUMBER_QNAME, String.class, null, value);
    }

}
