/* 
*  Copyright (c) 2018 Georgia-Pacific.  All rights reserved.
*  This software is the confidential and proprietary information of Georgia-Pacific.
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 12:51:38 AM IST 
//


@javax.xml.bind.annotation.XmlSchema(namespace = "http://businessobjects.com/service/Service_Realtime_DQ_SAP_Address_Cleanse_Suggestions/output", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gp.businessobjects.service.addr.suggestions.output;
