/* 
*  Copyright (c) 2018 Georgia-Pacific.  All rights reserved.
*  This software is the confidential and proprietary information of Georgia-Pacific.
*/

package com.gp.commerce.core.dto.onesource;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "taxCalculationFault", targetNamespace = "http://www.sabrix.com/services/taxcalculationservice/2011-09-01")
public class TaxCalculationFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TaxCalculationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TaxCalculationFault_Exception(String message, TaxCalculationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TaxCalculationFault_Exception(String message, TaxCalculationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sabrix.services.taxcalculationservice._2011_09_01.TaxCalculationFault
     */
    public TaxCalculationFault getFaultInfo() {
        return faultInfo;
    }

}
