/*
 *  Copyright (c) 2018 Georgia-Pacific.  All rights reserved.
 *  This software is the confidential and proprietary information of Georgia-Pacific.
 */
package com.gp.commerce.core.calculation.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.gp.commerce.core.dto.onesource.ObjectFactory;
import com.gp.commerce.core.dto.onesource.TaxCalculationFault_Exception;
import com.gp.commerce.core.dto.onesource.TaxCalculationRequest;
import com.gp.commerce.core.dto.onesource.TaxCalculationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "TaxCalculationService", targetNamespace = "http://www.sabrix.com/services/taxcalculationservice/2011-09-01")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GPOneSourceTaxService {


	/**
	 * Calculates tax and throws {@link TaxCalculationFault_Exception} on error.
	 *
	 * @param parameters the parameters
	 * @return {@link TaxCalculationResponse}
	 * @throws TaxCalculationFault_Exception the tax calculation fault exception
	 */
    @WebMethod(operationName = "CalculateTax")
    @WebResult(name = "taxCalculationResponse", targetNamespace = "http://www.sabrix.com/services/taxcalculationservice/2011-09-01", partName = "parameters")
	TaxCalculationResponse calculateTax(
        @WebParam(name = "taxCalculationRequest", targetNamespace = "http://www.sabrix.com/services/taxcalculationservice/2011-09-01", partName = "parameters")
        TaxCalculationRequest parameters)
        throws TaxCalculationFault_Exception
    ;

}

