//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Value" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}OptionalLocalizedStringType" maxOccurs="unbounded"/>
 *         &lt;element name="UrlValue" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}OptionalLocalizedUrlType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ExternalIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeType", propOrder = {
    "value",
    "urlValue"
})
public class AttributeType {

    @XmlElement(name = "Value")
    protected List<OptionalLocalizedStringType> value;
    @XmlElement(name = "UrlValue")
    protected List<OptionalLocalizedUrlType> urlValue;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptionalLocalizedStringType }
     * 
     * 
     */
    public List<OptionalLocalizedStringType> getValue() {
        if (value == null) {
            value = new ArrayList<OptionalLocalizedStringType>();
        }
        return this.value;
    }

    /**
     * Gets the value of the urlValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urlValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrlValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptionalLocalizedUrlType }
     * 
     * 
     */
    public List<OptionalLocalizedUrlType> getUrlValue() {
        if (urlValue == null) {
            urlValue = new ArrayList<OptionalLocalizedUrlType>();
        }
        return this.urlValue;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
