//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ExternalId" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ExternalIdType" minOccurs="0"/>
 *         &lt;element name="CategoryPath" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}CategoriesType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Names" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NamesType" minOccurs="0"/>
 *         &lt;element name="CategoryPageUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="CategoryPageUrls" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}CategoryPageUrlsType" minOccurs="0"/>
 *         &lt;element name="ReviewsPageTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReviewsPageTitles" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}PageTitlesType" minOccurs="0"/>
 *         &lt;element name="ReviewsPageMetaDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReviewsPageMetaDescriptions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}MetaDescriptionsType" minOccurs="0"/>
 *         &lt;element name="Attributes" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}AttributesType" minOccurs="0"/>
 *         &lt;element name="NumNativeQuestions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumQuestions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumStories" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumNativeAnswers" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumAnswers" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="Questions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}QuestionsType" minOccurs="0"/>
 *         &lt;element name="Stories" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}StoriesType" minOccurs="0"/>
 *         &lt;element name="ImageUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ImageUrls" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}LocalizedUrlsType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryType", propOrder = {

})
public class CategoryType {

    @XmlElement(name = "ExternalId")
    protected String externalId;
    @XmlElement(name = "CategoryPath")
    protected CategoriesType categoryPath;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Names")
    protected NamesType names;
    @XmlElement(name = "CategoryPageUrl")
    @XmlSchemaType(name = "anyURI")
    protected String categoryPageUrl;
    @XmlElement(name = "CategoryPageUrls")
    protected CategoryPageUrlsType categoryPageUrls;
    @XmlElement(name = "ReviewsPageTitle")
    protected String reviewsPageTitle;
    @XmlElement(name = "ReviewsPageTitles")
    protected PageTitlesType reviewsPageTitles;
    @XmlElement(name = "ReviewsPageMetaDescription")
    protected String reviewsPageMetaDescription;
    @XmlElement(name = "ReviewsPageMetaDescriptions")
    protected MetaDescriptionsType reviewsPageMetaDescriptions;
    @XmlElement(name = "Attributes")
    protected AttributesType attributes;
    @XmlElement(name = "NumNativeQuestions")
    protected Integer numNativeQuestions;
    @XmlElement(name = "NumQuestions")
    protected Integer numQuestions;
    @XmlElement(name = "NumStories")
    protected Integer numStories;
    @XmlElement(name = "NumNativeAnswers")
    protected Integer numNativeAnswers;
    @XmlElement(name = "NumAnswers")
    protected Integer numAnswers;
    @XmlElement(name = "Questions")
    protected QuestionsType questions;
    @XmlElement(name = "Stories")
    protected StoriesType stories;
    @XmlElement(name = "ImageUrl")
    @XmlSchemaType(name = "anyURI")
    protected String imageUrl;
    @XmlElement(name = "ImageUrls")
    protected LocalizedUrlsType imageUrls;

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the categoryPath property.
     * 
     * @return
     *     possible object is
     *     {@link CategoriesType }
     *     
     */
    public CategoriesType getCategoryPath() {
        return categoryPath;
    }

    /**
     * Sets the value of the categoryPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoriesType }
     *     
     */
    public void setCategoryPath(CategoriesType value) {
        this.categoryPath = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the names property.
     * 
     * @return
     *     possible object is
     *     {@link NamesType }
     *     
     */
    public NamesType getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamesType }
     *     
     */
    public void setNames(NamesType value) {
        this.names = value;
    }

    /**
     * Gets the value of the categoryPageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryPageUrl() {
        return categoryPageUrl;
    }

    /**
     * Sets the value of the categoryPageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryPageUrl(String value) {
        this.categoryPageUrl = value;
    }

    /**
     * Gets the value of the categoryPageUrls property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryPageUrlsType }
     *     
     */
    public CategoryPageUrlsType getCategoryPageUrls() {
        return categoryPageUrls;
    }

    /**
     * Sets the value of the categoryPageUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryPageUrlsType }
     *     
     */
    public void setCategoryPageUrls(CategoryPageUrlsType value) {
        this.categoryPageUrls = value;
    }

    /**
     * Gets the value of the reviewsPageTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewsPageTitle() {
        return reviewsPageTitle;
    }

    /**
     * Sets the value of the reviewsPageTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewsPageTitle(String value) {
        this.reviewsPageTitle = value;
    }

    /**
     * Gets the value of the reviewsPageTitles property.
     * 
     * @return
     *     possible object is
     *     {@link PageTitlesType }
     *     
     */
    public PageTitlesType getReviewsPageTitles() {
        return reviewsPageTitles;
    }

    /**
     * Sets the value of the reviewsPageTitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageTitlesType }
     *     
     */
    public void setReviewsPageTitles(PageTitlesType value) {
        this.reviewsPageTitles = value;
    }

    /**
     * Gets the value of the reviewsPageMetaDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewsPageMetaDescription() {
        return reviewsPageMetaDescription;
    }

    /**
     * Sets the value of the reviewsPageMetaDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewsPageMetaDescription(String value) {
        this.reviewsPageMetaDescription = value;
    }

    /**
     * Gets the value of the reviewsPageMetaDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDescriptionsType }
     *     
     */
    public MetaDescriptionsType getReviewsPageMetaDescriptions() {
        return reviewsPageMetaDescriptions;
    }

    /**
     * Sets the value of the reviewsPageMetaDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDescriptionsType }
     *     
     */
    public void setReviewsPageMetaDescriptions(MetaDescriptionsType value) {
        this.reviewsPageMetaDescriptions = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the numNativeQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumNativeQuestions() {
        return numNativeQuestions;
    }

    /**
     * Sets the value of the numNativeQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumNativeQuestions(Integer value) {
        this.numNativeQuestions = value;
    }

    /**
     * Gets the value of the numQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumQuestions() {
        return numQuestions;
    }

    /**
     * Sets the value of the numQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumQuestions(Integer value) {
        this.numQuestions = value;
    }

    /**
     * Gets the value of the numStories property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumStories() {
        return numStories;
    }

    /**
     * Sets the value of the numStories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumStories(Integer value) {
        this.numStories = value;
    }

    /**
     * Gets the value of the numNativeAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumNativeAnswers() {
        return numNativeAnswers;
    }

    /**
     * Sets the value of the numNativeAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumNativeAnswers(Integer value) {
        this.numNativeAnswers = value;
    }

    /**
     * Gets the value of the numAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumAnswers() {
        return numAnswers;
    }

    /**
     * Sets the value of the numAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumAnswers(Integer value) {
        this.numAnswers = value;
    }

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link QuestionsType }
     *     
     */
    public QuestionsType getQuestions() {
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuestionsType }
     *     
     */
    public void setQuestions(QuestionsType value) {
        this.questions = value;
    }

    /**
     * Gets the value of the stories property.
     * 
     * @return
     *     possible object is
     *     {@link StoriesType }
     *     
     */
    public StoriesType getStories() {
        return stories;
    }

    /**
     * Sets the value of the stories property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoriesType }
     *     
     */
    public void setStories(StoriesType value) {
        this.stories = value;
    }

    /**
     * Gets the value of the imageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Sets the value of the imageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageUrl(String value) {
        this.imageUrl = value;
    }

    /**
     * Gets the value of the imageUrls property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedUrlsType }
     *     
     */
    public LocalizedUrlsType getImageUrls() {
        return imageUrls;
    }

    /**
     * Sets the value of the imageUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedUrlsType }
     *     
     */
    public void setImageUrls(LocalizedUrlsType value) {
        this.imageUrls = value;
    }

}
