//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentRatingFeedbackType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentRatingFeedbackType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Range" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NumRatingFeedbacks" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ComputedScore" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="AverageScore" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentRatingFeedbackType", propOrder = {

})
public class ContentRatingFeedbackType {

    @XmlElement(name = "Range")
    protected int range;
    @XmlElement(name = "NumRatingFeedbacks")
    protected int numRatingFeedbacks;
    @XmlElement(name = "ComputedScore")
    protected Float computedScore;
    @XmlElement(name = "AverageScore")
    protected Float averageScore;

    /**
     * Gets the value of the range property.
     * 
     */
    public int getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     */
    public void setRange(int value) {
        this.range = value;
    }

    /**
     * Gets the value of the numRatingFeedbacks property.
     * 
     */
    public int getNumRatingFeedbacks() {
        return numRatingFeedbacks;
    }

    /**
     * Sets the value of the numRatingFeedbacks property.
     * 
     */
    public void setNumRatingFeedbacks(int value) {
        this.numRatingFeedbacks = value;
    }

    /**
     * Gets the value of the computedScore property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getComputedScore() {
        return computedScore;
    }

    /**
     * Sets the value of the computedScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setComputedScore(Float value) {
        this.computedScore = value;
    }

    /**
     * Gets the value of the averageScore property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAverageScore() {
        return averageScore;
    }

    /**
     * Sets the value of the averageScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAverageScore(Float value) {
        this.averageScore = value;
    }

}
