//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocaleDistributionItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocaleDistributionItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="DisplayLocale" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}LocaleType"/>
 *         &lt;element name="ReviewStatistics" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ReviewStatisticsType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocaleDistributionItemType", propOrder = {

})
public class LocaleDistributionItemType {

    @XmlElement(name = "DisplayLocale", required = true)
    protected String displayLocale;
    @XmlElement(name = "ReviewStatistics", required = true)
    protected ReviewStatisticsType reviewStatistics;

    /**
     * Gets the value of the displayLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayLocale() {
        return displayLocale;
    }

    /**
     * Sets the value of the displayLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayLocale(String value) {
        this.displayLocale = value;
    }

    /**
     * Gets the value of the reviewStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewStatisticsType }
     *     
     */
    public ReviewStatisticsType getReviewStatistics() {
        return reviewStatistics;
    }

    /**
     * Sets the value of the reviewStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewStatisticsType }
     *     
     */
    public void setReviewStatistics(ReviewStatisticsType value) {
        this.reviewStatistics = value;
    }

}
