//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarkupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarkupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="HighlightText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PlainText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LinkText" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}LinkTextType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarkupType", propOrder = {
    "highlightTextOrPlainTextOrLinkText"
})
public class MarkupType {

    @XmlElementRefs({
        @XmlElementRef(name = "PlainText", namespace = "http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "HighlightText", namespace = "http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LinkText", namespace = "http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> highlightTextOrPlainTextOrLinkText;

    /**
     * Gets the value of the highlightTextOrPlainTextOrLinkText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the highlightTextOrPlainTextOrLinkText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHighlightTextOrPlainTextOrLinkText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link LinkTextType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getHighlightTextOrPlainTextOrLinkText() {
        if (highlightTextOrPlainTextOrLinkText == null) {
            highlightTextOrPlainTextOrLinkText = new ArrayList<JAXBElement<?>>();
        }
        return this.highlightTextOrPlainTextOrLinkText;
    }

}
