//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bazaarvoice.gp.feed.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Feed_QNAME = new QName("http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", "Feed");
    private final static QName _MarkupTypePlainText_QNAME = new QName("http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", "PlainText");
    private final static QName _MarkupTypeHighlightText_QNAME = new QName("http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", "HighlightText");
    private final static QName _MarkupTypeLinkText_QNAME = new QName("http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", "LinkText");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bazaarvoice.gp.feed.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TagDistributionType }
     * 
     */
    public TagDistributionType createTagDistributionType() {
        return new TagDistributionType();
    }

    /**
     * Create an instance of {@link TagsType }
     * 
     */
    public TagsType createTagsType() {
        return new TagsType();
    }

    /**
     * Create an instance of {@link FeedType }
     * 
     */
    public FeedType createFeedType() {
        return new FeedType();
    }

    /**
     * Create an instance of {@link FeedbackVotingDimensionType }
     * 
     */
    public FeedbackVotingDimensionType createFeedbackVotingDimensionType() {
        return new FeedbackVotingDimensionType();
    }

    /**
     * Create an instance of {@link RatingValuesType }
     * 
     */
    public RatingValuesType createRatingValuesType() {
        return new RatingValuesType();
    }

    /**
     * Create an instance of {@link TagDistributionItemType }
     * 
     */
    public TagDistributionItemType createTagDistributionItemType() {
        return new TagDistributionItemType();
    }

    /**
     * Create an instance of {@link ContextDataValuesType }
     * 
     */
    public ContextDataValuesType createContextDataValuesType() {
        return new ContextDataValuesType();
    }

    /**
     * Create an instance of {@link IsbnsType }
     * 
     */
    public IsbnsType createIsbnsType() {
        return new IsbnsType();
    }

    /**
     * Create an instance of {@link PhotoType }
     * 
     */
    public PhotoType createPhotoType() {
        return new PhotoType();
    }

    /**
     * Create an instance of {@link NamesType }
     * 
     */
    public NamesType createNamesType() {
        return new NamesType();
    }

    /**
     * Create an instance of {@link ProductReferenceType }
     * 
     */
    public ProductReferenceType createProductReferenceType() {
        return new ProductReferenceType();
    }

    /**
     * Create an instance of {@link AverageRatingValuesType }
     * 
     */
    public AverageRatingValuesType createAverageRatingValuesType() {
        return new AverageRatingValuesType();
    }

    /**
     * Create an instance of {@link CategoryItemType }
     * 
     */
    public CategoryItemType createCategoryItemType() {
        return new CategoryItemType();
    }

    /**
     * Create an instance of {@link RatingDistributionType }
     * 
     */
    public RatingDistributionType createRatingDistributionType() {
        return new RatingDistributionType();
    }

    /**
     * Create an instance of {@link FeedbackType }
     * 
     */
    public FeedbackType createFeedbackType() {
        return new FeedbackType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link OptionalLocalizedUrlType }
     * 
     */
    public OptionalLocalizedUrlType createOptionalLocalizedUrlType() {
        return new OptionalLocalizedUrlType();
    }

    /**
     * Create an instance of {@link FeedbackVotingValuesType }
     * 
     */
    public FeedbackVotingValuesType createFeedbackVotingValuesType() {
        return new FeedbackVotingValuesType();
    }

    /**
     * Create an instance of {@link ContextDataDimensionType }
     * 
     */
    public ContextDataDimensionType createContextDataDimensionType() {
        return new ContextDataDimensionType();
    }

    /**
     * Create an instance of {@link PhotoSizeType }
     * 
     */
    public PhotoSizeType createPhotoSizeType() {
        return new PhotoSizeType();
    }

    /**
     * Create an instance of {@link ReviewType }
     * 
     */
    public ReviewType createReviewType() {
        return new ReviewType();
    }

    /**
     * Create an instance of {@link RatingValueType }
     * 
     */
    public RatingValueType createRatingValueType() {
        return new RatingValueType();
    }

    /**
     * Create an instance of {@link ContentRatingFeedbackType }
     * 
     */
    public ContentRatingFeedbackType createContentRatingFeedbackType() {
        return new ContentRatingFeedbackType();
    }

    /**
     * Create an instance of {@link LocaleDistributionType }
     * 
     */
    public LocaleDistributionType createLocaleDistributionType() {
        return new LocaleDistributionType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link CommentsType }
     * 
     */
    public CommentsType createCommentsType() {
        return new CommentsType();
    }

    /**
     * Create an instance of {@link StoriesType }
     * 
     */
    public StoriesType createStoriesType() {
        return new StoriesType();
    }

    /**
     * Create an instance of {@link TagsInDimensionType }
     * 
     */
    public TagsInDimensionType createTagsInDimensionType() {
        return new TagsInDimensionType();
    }

    /**
     * Create an instance of {@link UpcsType }
     * 
     */
    public UpcsType createUpcsType() {
        return new UpcsType();
    }

    /**
     * Create an instance of {@link CategoryDelayType }
     * 
     */
    public CategoryDelayType createCategoryDelayType() {
        return new CategoryDelayType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link OptionalLocalizedStringType }
     * 
     */
    public OptionalLocalizedStringType createOptionalLocalizedStringType() {
        return new OptionalLocalizedStringType();
    }

    /**
     * Create an instance of {@link AdditionalFieldType }
     * 
     */
    public AdditionalFieldType createAdditionalFieldType() {
        return new AdditionalFieldType();
    }

    /**
     * Create an instance of {@link AttributesType }
     * 
     */
    public AttributesType createAttributesType() {
        return new AttributesType();
    }

    /**
     * Create an instance of {@link FeedbackVotingValueType }
     * 
     */
    public FeedbackVotingValueType createFeedbackVotingValueType() {
        return new FeedbackVotingValueType();
    }

    /**
     * Create an instance of {@link AnswerType }
     * 
     */
    public AnswerType createAnswerType() {
        return new AnswerType();
    }

    /**
     * Create an instance of {@link CategoriesType }
     * 
     */
    public CategoriesType createCategoriesType() {
        return new CategoriesType();
    }

    /**
     * Create an instance of {@link VideosType }
     * 
     */
    public VideosType createVideosType() {
        return new VideosType();
    }

    /**
     * Create an instance of {@link BadgeType }
     * 
     */
    public BadgeType createBadgeType() {
        return new BadgeType();
    }

    /**
     * Create an instance of {@link ClientResponsesType }
     * 
     */
    public ClientResponsesType createClientResponsesType() {
        return new ClientResponsesType();
    }

    /**
     * Create an instance of {@link LocalizedUrlsType }
     * 
     */
    public LocalizedUrlsType createLocalizedUrlsType() {
        return new LocalizedUrlsType();
    }

    /**
     * Create an instance of {@link BrandType }
     * 
     */
    public BrandType createBrandType() {
        return new BrandType();
    }

    /**
     * Create an instance of {@link EansType }
     * 
     */
    public EansType createEansType() {
        return new EansType();
    }

    /**
     * Create an instance of {@link RatingDistributionItemType }
     * 
     */
    public RatingDistributionItemType createRatingDistributionItemType() {
        return new RatingDistributionItemType();
    }

    /**
     * Create an instance of {@link QuestionsType }
     * 
     */
    public QuestionsType createQuestionsType() {
        return new QuestionsType();
    }

    /**
     * Create an instance of {@link RatingDimensionType }
     * 
     */
    public RatingDimensionType createRatingDimensionType() {
        return new RatingDimensionType();
    }

    /**
     * Create an instance of {@link StoryType }
     * 
     */
    public StoryType createStoryType() {
        return new StoryType();
    }

    /**
     * Create an instance of {@link AnswersType }
     * 
     */
    public AnswersType createAnswersType() {
        return new AnswersType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link CategoryItemsType }
     * 
     */
    public CategoryItemsType createCategoryItemsType() {
        return new CategoryItemsType();
    }

    /**
     * Create an instance of {@link LocalizedUrlType }
     * 
     */
    public LocalizedUrlType createLocalizedUrlType() {
        return new LocalizedUrlType();
    }

    /**
     * Create an instance of {@link ManufacturerPartNumbersType }
     * 
     */
    public ManufacturerPartNumbersType createManufacturerPartNumbersType() {
        return new ManufacturerPartNumbersType();
    }

    /**
     * Create an instance of {@link ProductPageUrlsType }
     * 
     */
    public ProductPageUrlsType createProductPageUrlsType() {
        return new ProductPageUrlsType();
    }

    /**
     * Create an instance of {@link VideoType }
     * 
     */
    public VideoType createVideoType() {
        return new VideoType();
    }

    /**
     * Create an instance of {@link ReviewsType }
     * 
     */
    public ReviewsType createReviewsType() {
        return new ReviewsType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link ProductReferencesType }
     * 
     */
    public ProductReferencesType createProductReferencesType() {
        return new ProductReferencesType();
    }

    /**
     * Create an instance of {@link PageTitlesType }
     * 
     */
    public PageTitlesType createPageTitlesType() {
        return new PageTitlesType();
    }

    /**
     * Create an instance of {@link PhotoSizesType }
     * 
     */
    public PhotoSizesType createPhotoSizesType() {
        return new PhotoSizesType();
    }

    /**
     * Create an instance of {@link ClientResponseType }
     * 
     */
    public ClientResponseType createClientResponseType() {
        return new ClientResponseType();
    }

    /**
     * Create an instance of {@link ContextDataValueType }
     * 
     */
    public ContextDataValueType createContextDataValueType() {
        return new ContextDataValueType();
    }

    /**
     * Create an instance of {@link AdditionalFieldsType }
     * 
     */
    public AdditionalFieldsType createAdditionalFieldsType() {
        return new AdditionalFieldsType();
    }

    /**
     * Create an instance of {@link MarkupType }
     * 
     */
    public MarkupType createMarkupType() {
        return new MarkupType();
    }

    /**
     * Create an instance of {@link BadgesType }
     * 
     */
    public BadgesType createBadgesType() {
        return new BadgesType();
    }

    /**
     * Create an instance of {@link ModelNumbersType }
     * 
     */
    public ModelNumbersType createModelNumbersType() {
        return new ModelNumbersType();
    }

    /**
     * Create an instance of {@link LocalizedStringType }
     * 
     */
    public LocalizedStringType createLocalizedStringType() {
        return new LocalizedStringType();
    }

    /**
     * Create an instance of {@link PhotosType }
     * 
     */
    public PhotosType createPhotosType() {
        return new PhotosType();
    }

    /**
     * Create an instance of {@link QuestionType }
     * 
     */
    public QuestionType createQuestionType() {
        return new QuestionType();
    }

    /**
     * Create an instance of {@link ReviewStatisticsType }
     * 
     */
    public ReviewStatisticsType createReviewStatisticsType() {
        return new ReviewStatisticsType();
    }

    /**
     * Create an instance of {@link ReviewStatisticsSlicesType }
     * 
     */
    public ReviewStatisticsSlicesType createReviewStatisticsSlicesType() {
        return new ReviewStatisticsSlicesType();
    }

    /**
     * Create an instance of {@link TagDistributionInDimensionType }
     * 
     */
    public TagDistributionInDimensionType createTagDistributionInDimensionType() {
        return new TagDistributionInDimensionType();
    }

    /**
     * Create an instance of {@link CategoryPageUrlsType }
     * 
     */
    public CategoryPageUrlsType createCategoryPageUrlsType() {
        return new CategoryPageUrlsType();
    }

    /**
     * Create an instance of {@link AverageRatingValueType }
     * 
     */
    public AverageRatingValueType createAverageRatingValueType() {
        return new AverageRatingValueType();
    }

    /**
     * Create an instance of {@link UserProfileReferenceType }
     * 
     */
    public UserProfileReferenceType createUserProfileReferenceType() {
        return new UserProfileReferenceType();
    }

    /**
     * Create an instance of {@link LinkTextType }
     * 
     */
    public LinkTextType createLinkTextType() {
        return new LinkTextType();
    }

    /**
     * Create an instance of {@link LocaleDistributionItemType }
     * 
     */
    public LocaleDistributionItemType createLocaleDistributionItemType() {
        return new LocaleDistributionItemType();
    }

    /**
     * Create an instance of {@link DescriptionsType }
     * 
     */
    public DescriptionsType createDescriptionsType() {
        return new DescriptionsType();
    }

    /**
     * Create an instance of {@link MetaDescriptionsType }
     * 
     */
    public MetaDescriptionsType createMetaDescriptionsType() {
        return new MetaDescriptionsType();
    }

    /**
     * Create an instance of {@link TagDistributionType.TagDimension }
     * 
     */
    public TagDistributionType.TagDimension createTagDistributionTypeTagDimension() {
        return new TagDistributionType.TagDimension();
    }

    /**
     * Create an instance of {@link TagsType.TagDimension }
     * 
     */
    public TagsType.TagDimension createTagsTypeTagDimension() {
        return new TagsType.TagDimension();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", name = "Feed")
    public JAXBElement<FeedType> createFeed(FeedType value) {
        return new JAXBElement<FeedType>(_Feed_QNAME, FeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", name = "PlainText", scope = MarkupType.class)
    public JAXBElement<String> createMarkupTypePlainText(String value) {
        return new JAXBElement<String>(_MarkupTypePlainText_QNAME, String.class, MarkupType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", name = "HighlightText", scope = MarkupType.class)
    public JAXBElement<String> createMarkupTypeHighlightText(String value) {
        return new JAXBElement<String>(_MarkupTypeHighlightText_QNAME, String.class, MarkupType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkTextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6", name = "LinkText", scope = MarkupType.class)
    public JAXBElement<LinkTextType> createMarkupTypeLinkText(LinkTextType value) {
        return new JAXBElement<LinkTextType>(_MarkupTypeLinkText_QNAME, LinkTextType.class, MarkupType.class, value);
    }

}
