//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExternalId" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ExternalIdType"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Names" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NamesType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Descriptions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}DescriptionsType" minOccurs="0"/>
 *         &lt;element name="Brand" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}BrandType" minOccurs="0"/>
 *         &lt;element name="Attributes" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}AttributesType" minOccurs="0"/>
 *         &lt;element name="NumNativeQuestions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumQuestions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumNativeAnswers" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumAnswers" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumReviews" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumStories" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="Questions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}QuestionsType" minOccurs="0"/>
 *         &lt;element name="Stories" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}StoriesType" minOccurs="0"/>
 *         &lt;element name="Category" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ExternalIdType" minOccurs="0"/>
 *         &lt;element name="CategoryItems" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}CategoryItemsType" minOccurs="0"/>
 *         &lt;element name="ProductPageUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ProductPageUrls" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ProductPageUrlsType" minOccurs="0"/>
 *         &lt;element name="ProductReviewsUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ReviewsPageTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReviewsPageTitles" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}PageTitlesType" minOccurs="0"/>
 *         &lt;element name="ReviewsPageMetaDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReviewsPageMetaDescriptions" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}MetaDescriptionsType" minOccurs="0"/>
 *         &lt;element name="ProductQuestionsUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ProductStoriesUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ImageUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ImageUrls" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}LocalizedUrlsType" minOccurs="0"/>
 *         &lt;element name="ModelNumbers" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ModelNumbersType" minOccurs="0"/>
 *         &lt;element name="ManufacturerPartNumbers" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ManufacturerPartNumbersType" minOccurs="0"/>
 *         &lt;element name="EANs" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}EansType" minOccurs="0"/>
 *         &lt;element name="UPCs" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}UpcsType" minOccurs="0"/>
 *         &lt;element name="ISBNs" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}IsbnsType" minOccurs="0"/>
 *         &lt;element name="ReviewStatistics" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ReviewStatisticsType" minOccurs="0"/>
 *         &lt;element name="NativeReviewStatistics" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ReviewStatisticsType" minOccurs="0"/>
 *         &lt;element name="Reviews" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ReviewsType" minOccurs="0"/>
 *         &lt;element name="Feedback" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}FeedbackType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ExternalIdType" />
 *       &lt;attribute name="removed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType", propOrder = {

})
public class ProductType {

    @XmlElement(name = "Source")
    protected String source;
    @XmlElement(name = "ExternalId", required = true)
    protected String externalId;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Names")
    protected NamesType names;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Descriptions")
    protected DescriptionsType descriptions;
    @XmlElement(name = "Brand")
    protected BrandType brand;
    @XmlElement(name = "Attributes")
    protected AttributesType attributes;
    @XmlElement(name = "NumNativeQuestions")
    protected Integer numNativeQuestions;
    @XmlElement(name = "NumQuestions")
    protected Integer numQuestions;
    @XmlElement(name = "NumNativeAnswers")
    protected Integer numNativeAnswers;
    @XmlElement(name = "NumAnswers")
    protected Integer numAnswers;
    @XmlElement(name = "NumReviews")
    protected Integer numReviews;
    @XmlElement(name = "NumStories")
    protected Integer numStories;
    @XmlElement(name = "Questions")
    protected QuestionsType questions;
    @XmlElement(name = "Stories")
    protected StoriesType stories;
    @XmlElement(name = "Category")
    protected String category;
    @XmlElement(name = "CategoryItems")
    protected CategoryItemsType categoryItems;
    @XmlElement(name = "ProductPageUrl")
    @XmlSchemaType(name = "anyURI")
    protected String productPageUrl;
    @XmlElement(name = "ProductPageUrls")
    protected ProductPageUrlsType productPageUrls;
    @XmlElement(name = "ProductReviewsUrl")
    @XmlSchemaType(name = "anyURI")
    protected String productReviewsUrl;
    @XmlElement(name = "ReviewsPageTitle")
    protected String reviewsPageTitle;
    @XmlElement(name = "ReviewsPageTitles")
    protected PageTitlesType reviewsPageTitles;
    @XmlElement(name = "ReviewsPageMetaDescription")
    protected String reviewsPageMetaDescription;
    @XmlElement(name = "ReviewsPageMetaDescriptions")
    protected MetaDescriptionsType reviewsPageMetaDescriptions;
    @XmlElement(name = "ProductQuestionsUrl")
    @XmlSchemaType(name = "anyURI")
    protected String productQuestionsUrl;
    @XmlElement(name = "ProductStoriesUrl")
    @XmlSchemaType(name = "anyURI")
    protected String productStoriesUrl;
    @XmlElement(name = "ImageUrl")
    @XmlSchemaType(name = "anyURI")
    protected String imageUrl;
    @XmlElement(name = "ImageUrls")
    protected LocalizedUrlsType imageUrls;
    @XmlElement(name = "ModelNumbers")
    protected ModelNumbersType modelNumbers;
    @XmlElement(name = "ManufacturerPartNumbers")
    protected ManufacturerPartNumbersType manufacturerPartNumbers;
    @XmlElement(name = "EANs")
    protected EansType eaNs;
    @XmlElement(name = "UPCs")
    protected UpcsType upCs;
    @XmlElement(name = "ISBNs")
    protected IsbnsType isbNs;
    @XmlElement(name = "ReviewStatistics")
    protected ReviewStatisticsType reviewStatistics;
    @XmlElement(name = "NativeReviewStatistics")
    protected ReviewStatisticsType nativeReviewStatistics;
    @XmlElement(name = "Reviews")
    protected ReviewsType reviews;
    @XmlElement(name = "Feedback")
    protected FeedbackType feedback;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "removed")
    protected Boolean removed;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the names property.
     * 
     * @return
     *     possible object is
     *     {@link NamesType }
     *     
     */
    public NamesType getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamesType }
     *     
     */
    public void setNames(NamesType value) {
        this.names = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionsType }
     *     
     */
    public DescriptionsType getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionsType }
     *     
     */
    public void setDescriptions(DescriptionsType value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link BrandType }
     *     
     */
    public BrandType getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandType }
     *     
     */
    public void setBrand(BrandType value) {
        this.brand = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the numNativeQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumNativeQuestions() {
        return numNativeQuestions;
    }

    /**
     * Sets the value of the numNativeQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumNativeQuestions(Integer value) {
        this.numNativeQuestions = value;
    }

    /**
     * Gets the value of the numQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumQuestions() {
        return numQuestions;
    }

    /**
     * Sets the value of the numQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumQuestions(Integer value) {
        this.numQuestions = value;
    }

    /**
     * Gets the value of the numNativeAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumNativeAnswers() {
        return numNativeAnswers;
    }

    /**
     * Sets the value of the numNativeAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumNativeAnswers(Integer value) {
        this.numNativeAnswers = value;
    }

    /**
     * Gets the value of the numAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumAnswers() {
        return numAnswers;
    }

    /**
     * Sets the value of the numAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumAnswers(Integer value) {
        this.numAnswers = value;
    }

    /**
     * Gets the value of the numReviews property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumReviews() {
        return numReviews;
    }

    /**
     * Sets the value of the numReviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumReviews(Integer value) {
        this.numReviews = value;
    }

    /**
     * Gets the value of the numStories property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumStories() {
        return numStories;
    }

    /**
     * Sets the value of the numStories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumStories(Integer value) {
        this.numStories = value;
    }

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link QuestionsType }
     *     
     */
    public QuestionsType getQuestions() {
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuestionsType }
     *     
     */
    public void setQuestions(QuestionsType value) {
        this.questions = value;
    }

    /**
     * Gets the value of the stories property.
     * 
     * @return
     *     possible object is
     *     {@link StoriesType }
     *     
     */
    public StoriesType getStories() {
        return stories;
    }

    /**
     * Sets the value of the stories property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoriesType }
     *     
     */
    public void setStories(StoriesType value) {
        this.stories = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the categoryItems property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryItemsType }
     *     
     */
    public CategoryItemsType getCategoryItems() {
        return categoryItems;
    }

    /**
     * Sets the value of the categoryItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryItemsType }
     *     
     */
    public void setCategoryItems(CategoryItemsType value) {
        this.categoryItems = value;
    }

    /**
     * Gets the value of the productPageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductPageUrl() {
        return productPageUrl;
    }

    /**
     * Sets the value of the productPageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductPageUrl(String value) {
        this.productPageUrl = value;
    }

    /**
     * Gets the value of the productPageUrls property.
     * 
     * @return
     *     possible object is
     *     {@link ProductPageUrlsType }
     *     
     */
    public ProductPageUrlsType getProductPageUrls() {
        return productPageUrls;
    }

    /**
     * Sets the value of the productPageUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductPageUrlsType }
     *     
     */
    public void setProductPageUrls(ProductPageUrlsType value) {
        this.productPageUrls = value;
    }

    /**
     * Gets the value of the productReviewsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductReviewsUrl() {
        return productReviewsUrl;
    }

    /**
     * Sets the value of the productReviewsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductReviewsUrl(String value) {
        this.productReviewsUrl = value;
    }

    /**
     * Gets the value of the reviewsPageTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewsPageTitle() {
        return reviewsPageTitle;
    }

    /**
     * Sets the value of the reviewsPageTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewsPageTitle(String value) {
        this.reviewsPageTitle = value;
    }

    /**
     * Gets the value of the reviewsPageTitles property.
     * 
     * @return
     *     possible object is
     *     {@link PageTitlesType }
     *     
     */
    public PageTitlesType getReviewsPageTitles() {
        return reviewsPageTitles;
    }

    /**
     * Sets the value of the reviewsPageTitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageTitlesType }
     *     
     */
    public void setReviewsPageTitles(PageTitlesType value) {
        this.reviewsPageTitles = value;
    }

    /**
     * Gets the value of the reviewsPageMetaDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewsPageMetaDescription() {
        return reviewsPageMetaDescription;
    }

    /**
     * Sets the value of the reviewsPageMetaDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewsPageMetaDescription(String value) {
        this.reviewsPageMetaDescription = value;
    }

    /**
     * Gets the value of the reviewsPageMetaDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDescriptionsType }
     *     
     */
    public MetaDescriptionsType getReviewsPageMetaDescriptions() {
        return reviewsPageMetaDescriptions;
    }

    /**
     * Sets the value of the reviewsPageMetaDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDescriptionsType }
     *     
     */
    public void setReviewsPageMetaDescriptions(MetaDescriptionsType value) {
        this.reviewsPageMetaDescriptions = value;
    }

    /**
     * Gets the value of the productQuestionsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductQuestionsUrl() {
        return productQuestionsUrl;
    }

    /**
     * Sets the value of the productQuestionsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductQuestionsUrl(String value) {
        this.productQuestionsUrl = value;
    }

    /**
     * Gets the value of the productStoriesUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductStoriesUrl() {
        return productStoriesUrl;
    }

    /**
     * Sets the value of the productStoriesUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductStoriesUrl(String value) {
        this.productStoriesUrl = value;
    }

    /**
     * Gets the value of the imageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Sets the value of the imageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageUrl(String value) {
        this.imageUrl = value;
    }

    /**
     * Gets the value of the imageUrls property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedUrlsType }
     *     
     */
    public LocalizedUrlsType getImageUrls() {
        return imageUrls;
    }

    /**
     * Sets the value of the imageUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedUrlsType }
     *     
     */
    public void setImageUrls(LocalizedUrlsType value) {
        this.imageUrls = value;
    }

    /**
     * Gets the value of the modelNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ModelNumbersType }
     *     
     */
    public ModelNumbersType getModelNumbers() {
        return modelNumbers;
    }

    /**
     * Sets the value of the modelNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelNumbersType }
     *     
     */
    public void setModelNumbers(ModelNumbersType value) {
        this.modelNumbers = value;
    }

    /**
     * Gets the value of the manufacturerPartNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ManufacturerPartNumbersType }
     *     
     */
    public ManufacturerPartNumbersType getManufacturerPartNumbers() {
        return manufacturerPartNumbers;
    }

    /**
     * Sets the value of the manufacturerPartNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufacturerPartNumbersType }
     *     
     */
    public void setManufacturerPartNumbers(ManufacturerPartNumbersType value) {
        this.manufacturerPartNumbers = value;
    }

    /**
     * Gets the value of the eaNs property.
     * 
     * @return
     *     possible object is
     *     {@link EansType }
     *     
     */
    public EansType getEANs() {
        return eaNs;
    }

    /**
     * Sets the value of the eaNs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EansType }
     *     
     */
    public void setEANs(EansType value) {
        this.eaNs = value;
    }

    /**
     * Gets the value of the upCs property.
     * 
     * @return
     *     possible object is
     *     {@link UpcsType }
     *     
     */
    public UpcsType getUPCs() {
        return upCs;
    }

    /**
     * Sets the value of the upCs property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpcsType }
     *     
     */
    public void setUPCs(UpcsType value) {
        this.upCs = value;
    }

    /**
     * Gets the value of the isbNs property.
     * 
     * @return
     *     possible object is
     *     {@link IsbnsType }
     *     
     */
    public IsbnsType getISBNs() {
        return isbNs;
    }

    /**
     * Sets the value of the isbNs property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsbnsType }
     *     
     */
    public void setISBNs(IsbnsType value) {
        this.isbNs = value;
    }

    /**
     * Gets the value of the reviewStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewStatisticsType }
     *     
     */
    public ReviewStatisticsType getReviewStatistics() {
        return reviewStatistics;
    }

    /**
     * Sets the value of the reviewStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewStatisticsType }
     *     
     */
    public void setReviewStatistics(ReviewStatisticsType value) {
        this.reviewStatistics = value;
    }

    /**
     * Gets the value of the nativeReviewStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewStatisticsType }
     *     
     */
    public ReviewStatisticsType getNativeReviewStatistics() {
        return nativeReviewStatistics;
    }

    /**
     * Sets the value of the nativeReviewStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewStatisticsType }
     *     
     */
    public void setNativeReviewStatistics(ReviewStatisticsType value) {
        this.nativeReviewStatistics = value;
    }

    /**
     * Gets the value of the reviews property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewsType }
     *     
     */
    public ReviewsType getReviews() {
        return reviews;
    }

    /**
     * Sets the value of the reviews property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewsType }
     *     
     */
    public void setReviews(ReviewsType value) {
        this.reviews = value;
    }

    /**
     * Gets the value of the feedback property.
     * 
     * @return
     *     possible object is
     *     {@link FeedbackType }
     *     
     */
    public FeedbackType getFeedback() {
        return feedback;
    }

    /**
     * Sets the value of the feedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedbackType }
     *     
     */
    public void setFeedback(FeedbackType value) {
        this.feedback = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the removed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRemoved() {
        if (removed == null) {
            return false;
        } else {
            return removed;
        }
    }

    /**
     * Sets the value of the removed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoved(Boolean value) {
        this.removed = value;
    }

}
