//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReviewStatisticsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReviewStatisticsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="StatisticsSliceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AverageOverallRating" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="OverallRatingRange" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TotalReviewCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RatingsOnlyReviewCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RecommendedCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AverageRatingValues" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}AverageRatingValuesType" minOccurs="0"/>
 *         &lt;element name="RatingDistribution" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}RatingDistributionType" minOccurs="0"/>
 *         &lt;element name="TagDistribution" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}TagDistributionType" minOccurs="0"/>
 *         &lt;element name="ReviewStatisticsSlices" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ReviewStatisticsSlicesType" minOccurs="0"/>
 *         &lt;element name="LocaleDistribution" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}LocaleDistributionType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReviewStatisticsType", propOrder = {

})
public class ReviewStatisticsType {

    @XmlElement(name = "StatisticsSliceName")
    protected String statisticsSliceName;
    @XmlElement(name = "AverageOverallRating")
    protected Float averageOverallRating;
    @XmlElement(name = "OverallRatingRange")
    protected Integer overallRatingRange;
    @XmlElement(name = "TotalReviewCount")
    protected int totalReviewCount;
    @XmlElement(name = "RatingsOnlyReviewCount")
    protected Integer ratingsOnlyReviewCount;
    @XmlElement(name = "RecommendedCount")
    protected Integer recommendedCount;
    @XmlElement(name = "AverageRatingValues")
    protected AverageRatingValuesType averageRatingValues;
    @XmlElement(name = "RatingDistribution")
    protected RatingDistributionType ratingDistribution;
    @XmlElement(name = "TagDistribution")
    protected TagDistributionType tagDistribution;
    @XmlElement(name = "ReviewStatisticsSlices")
    protected ReviewStatisticsSlicesType reviewStatisticsSlices;
    @XmlElement(name = "LocaleDistribution")
    protected LocaleDistributionType localeDistribution;

    /**
     * Gets the value of the statisticsSliceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatisticsSliceName() {
        return statisticsSliceName;
    }

    /**
     * Sets the value of the statisticsSliceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatisticsSliceName(String value) {
        this.statisticsSliceName = value;
    }

    /**
     * Gets the value of the averageOverallRating property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAverageOverallRating() {
        return averageOverallRating;
    }

    /**
     * Sets the value of the averageOverallRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAverageOverallRating(Float value) {
        this.averageOverallRating = value;
    }

    /**
     * Gets the value of the overallRatingRange property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOverallRatingRange() {
        return overallRatingRange;
    }

    /**
     * Sets the value of the overallRatingRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOverallRatingRange(Integer value) {
        this.overallRatingRange = value;
    }

    /**
     * Gets the value of the totalReviewCount property.
     * 
     */
    public int getTotalReviewCount() {
        return totalReviewCount;
    }

    /**
     * Sets the value of the totalReviewCount property.
     * 
     */
    public void setTotalReviewCount(int value) {
        this.totalReviewCount = value;
    }

    /**
     * Gets the value of the ratingsOnlyReviewCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRatingsOnlyReviewCount() {
        return ratingsOnlyReviewCount;
    }

    /**
     * Sets the value of the ratingsOnlyReviewCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRatingsOnlyReviewCount(Integer value) {
        this.ratingsOnlyReviewCount = value;
    }

    /**
     * Gets the value of the recommendedCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecommendedCount() {
        return recommendedCount;
    }

    /**
     * Sets the value of the recommendedCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecommendedCount(Integer value) {
        this.recommendedCount = value;
    }

    /**
     * Gets the value of the averageRatingValues property.
     * 
     * @return
     *     possible object is
     *     {@link AverageRatingValuesType }
     *     
     */
    public AverageRatingValuesType getAverageRatingValues() {
        return averageRatingValues;
    }

    /**
     * Sets the value of the averageRatingValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link AverageRatingValuesType }
     *     
     */
    public void setAverageRatingValues(AverageRatingValuesType value) {
        this.averageRatingValues = value;
    }

    /**
     * Gets the value of the ratingDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link RatingDistributionType }
     *     
     */
    public RatingDistributionType getRatingDistribution() {
        return ratingDistribution;
    }

    /**
     * Sets the value of the ratingDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingDistributionType }
     *     
     */
    public void setRatingDistribution(RatingDistributionType value) {
        this.ratingDistribution = value;
    }

    /**
     * Gets the value of the tagDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link TagDistributionType }
     *     
     */
    public TagDistributionType getTagDistribution() {
        return tagDistribution;
    }

    /**
     * Sets the value of the tagDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagDistributionType }
     *     
     */
    public void setTagDistribution(TagDistributionType value) {
        this.tagDistribution = value;
    }

    /**
     * Gets the value of the reviewStatisticsSlices property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewStatisticsSlicesType }
     *     
     */
    public ReviewStatisticsSlicesType getReviewStatisticsSlices() {
        return reviewStatisticsSlices;
    }

    /**
     * Sets the value of the reviewStatisticsSlices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewStatisticsSlicesType }
     *     
     */
    public void setReviewStatisticsSlices(ReviewStatisticsSlicesType value) {
        this.reviewStatisticsSlices = value;
    }

    /**
     * Gets the value of the localeDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link LocaleDistributionType }
     *     
     */
    public LocaleDistributionType getLocaleDistribution() {
        return localeDistribution;
    }

    /**
     * Sets the value of the localeDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocaleDistributionType }
     *     
     */
    public void setLocaleDistribution(LocaleDistributionType value) {
        this.localeDistribution = value;
    }

}
