//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:04:03 AM IST 
//


package com.bazaarvoice.gp.feed.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for StoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ModerationStatus" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ModerationStatusType" minOccurs="0"/>
 *         &lt;element name="LastModificationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SubmissionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="NumFeedbacks" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumPositiveFeedbacks" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="NumNegativeFeedbacks" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="StoryRatingFeedback" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ContentRatingFeedbackType" minOccurs="0"/>
 *         &lt;element name="Badges" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}BadgesType" minOccurs="0"/>
 *         &lt;element name="UserProfileReference" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}UserProfileReferenceType" minOccurs="0"/>
 *         &lt;element name="UserNickname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UserLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContextDataValues" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ContextDataValuesType" minOccurs="0"/>
 *         &lt;element name="Photos" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}PhotosType" minOccurs="0"/>
 *         &lt;element name="Videos" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}VideosType" minOccurs="0"/>
 *         &lt;element name="ProductReferences" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ProductReferencesType" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StoryText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumComments" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}NonNegativeInt" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}CommentsType" minOccurs="0"/>
 *         &lt;element name="ClientResponses" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ClientResponsesType" minOccurs="0"/>
 *         &lt;element name="AdditionalFields" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}AdditionalFieldsType" minOccurs="0"/>
 *         &lt;element name="Tags" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}TagsType" minOccurs="0"/>
 *         &lt;element name="SubjectStoriesDeepLinkedUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="DisplayLocale" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}LocaleType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.bazaarvoice.com/xs/PRR/SyndicationFeed/5.6}ExternalIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoryType", propOrder = {

})
public class StoryType {

    @XmlElement(name = "ModerationStatus")
    @XmlSchemaType(name = "NMTOKEN")
    protected ModerationStatusType moderationStatus;
    @XmlElement(name = "LastModificationTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModificationTime;
    @XmlElement(name = "SubmissionTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionTime;
    @XmlElement(name = "NumFeedbacks")
    protected Integer numFeedbacks;
    @XmlElement(name = "NumPositiveFeedbacks")
    protected Integer numPositiveFeedbacks;
    @XmlElement(name = "NumNegativeFeedbacks")
    protected Integer numNegativeFeedbacks;
    @XmlElement(name = "StoryRatingFeedback")
    protected ContentRatingFeedbackType storyRatingFeedback;
    @XmlElement(name = "Badges")
    protected BadgesType badges;
    @XmlElement(name = "UserProfileReference")
    protected UserProfileReferenceType userProfileReference;
    @XmlElement(name = "UserNickname")
    protected String userNickname;
    @XmlElement(name = "UserLocation")
    protected String userLocation;
    @XmlElement(name = "ContextDataValues")
    protected ContextDataValuesType contextDataValues;
    @XmlElement(name = "Photos")
    protected PhotosType photos;
    @XmlElement(name = "Videos")
    protected VideosType videos;
    @XmlElement(name = "ProductReferences")
    protected ProductReferencesType productReferences;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "StoryText")
    protected String storyText;
    @XmlElement(name = "NumComments")
    protected Integer numComments;
    @XmlElement(name = "Comments")
    protected CommentsType comments;
    @XmlElement(name = "ClientResponses")
    protected ClientResponsesType clientResponses;
    @XmlElement(name = "AdditionalFields")
    protected AdditionalFieldsType additionalFields;
    @XmlElement(name = "Tags")
    protected TagsType tags;
    @XmlElement(name = "SubjectStoriesDeepLinkedUrl")
    @XmlSchemaType(name = "anyURI")
    protected String subjectStoriesDeepLinkedUrl;
    @XmlElement(name = "DisplayLocale")
    protected String displayLocale;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the moderationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ModerationStatusType }
     *     
     */
    public ModerationStatusType getModerationStatus() {
        return moderationStatus;
    }

    /**
     * Sets the value of the moderationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModerationStatusType }
     *     
     */
    public void setModerationStatus(ModerationStatusType value) {
        this.moderationStatus = value;
    }

    /**
     * Gets the value of the lastModificationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModificationTime() {
        return lastModificationTime;
    }

    /**
     * Sets the value of the lastModificationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModificationTime(XMLGregorianCalendar value) {
        this.lastModificationTime = value;
    }

    /**
     * Gets the value of the submissionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionTime() {
        return submissionTime;
    }

    /**
     * Sets the value of the submissionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionTime(XMLGregorianCalendar value) {
        this.submissionTime = value;
    }

    /**
     * Gets the value of the numFeedbacks property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumFeedbacks() {
        return numFeedbacks;
    }

    /**
     * Sets the value of the numFeedbacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumFeedbacks(Integer value) {
        this.numFeedbacks = value;
    }

    /**
     * Gets the value of the numPositiveFeedbacks property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumPositiveFeedbacks() {
        return numPositiveFeedbacks;
    }

    /**
     * Sets the value of the numPositiveFeedbacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumPositiveFeedbacks(Integer value) {
        this.numPositiveFeedbacks = value;
    }

    /**
     * Gets the value of the numNegativeFeedbacks property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumNegativeFeedbacks() {
        return numNegativeFeedbacks;
    }

    /**
     * Sets the value of the numNegativeFeedbacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumNegativeFeedbacks(Integer value) {
        this.numNegativeFeedbacks = value;
    }

    /**
     * Gets the value of the storyRatingFeedback property.
     * 
     * @return
     *     possible object is
     *     {@link ContentRatingFeedbackType }
     *     
     */
    public ContentRatingFeedbackType getStoryRatingFeedback() {
        return storyRatingFeedback;
    }

    /**
     * Sets the value of the storyRatingFeedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentRatingFeedbackType }
     *     
     */
    public void setStoryRatingFeedback(ContentRatingFeedbackType value) {
        this.storyRatingFeedback = value;
    }

    /**
     * Gets the value of the badges property.
     * 
     * @return
     *     possible object is
     *     {@link BadgesType }
     *     
     */
    public BadgesType getBadges() {
        return badges;
    }

    /**
     * Sets the value of the badges property.
     * 
     * @param value
     *     allowed object is
     *     {@link BadgesType }
     *     
     */
    public void setBadges(BadgesType value) {
        this.badges = value;
    }

    /**
     * Gets the value of the userProfileReference property.
     * 
     * @return
     *     possible object is
     *     {@link UserProfileReferenceType }
     *     
     */
    public UserProfileReferenceType getUserProfileReference() {
        return userProfileReference;
    }

    /**
     * Sets the value of the userProfileReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserProfileReferenceType }
     *     
     */
    public void setUserProfileReference(UserProfileReferenceType value) {
        this.userProfileReference = value;
    }

    /**
     * Gets the value of the userNickname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * Sets the value of the userNickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserNickname(String value) {
        this.userNickname = value;
    }

    /**
     * Gets the value of the userLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLocation() {
        return userLocation;
    }

    /**
     * Sets the value of the userLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLocation(String value) {
        this.userLocation = value;
    }

    /**
     * Gets the value of the contextDataValues property.
     * 
     * @return
     *     possible object is
     *     {@link ContextDataValuesType }
     *     
     */
    public ContextDataValuesType getContextDataValues() {
        return contextDataValues;
    }

    /**
     * Sets the value of the contextDataValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextDataValuesType }
     *     
     */
    public void setContextDataValues(ContextDataValuesType value) {
        this.contextDataValues = value;
    }

    /**
     * Gets the value of the photos property.
     * 
     * @return
     *     possible object is
     *     {@link PhotosType }
     *     
     */
    public PhotosType getPhotos() {
        return photos;
    }

    /**
     * Sets the value of the photos property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhotosType }
     *     
     */
    public void setPhotos(PhotosType value) {
        this.photos = value;
    }

    /**
     * Gets the value of the videos property.
     * 
     * @return
     *     possible object is
     *     {@link VideosType }
     *     
     */
    public VideosType getVideos() {
        return videos;
    }

    /**
     * Sets the value of the videos property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideosType }
     *     
     */
    public void setVideos(VideosType value) {
        this.videos = value;
    }

    /**
     * Gets the value of the productReferences property.
     * 
     * @return
     *     possible object is
     *     {@link ProductReferencesType }
     *     
     */
    public ProductReferencesType getProductReferences() {
        return productReferences;
    }

    /**
     * Sets the value of the productReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductReferencesType }
     *     
     */
    public void setProductReferences(ProductReferencesType value) {
        this.productReferences = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the storyText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoryText() {
        return storyText;
    }

    /**
     * Sets the value of the storyText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoryText(String value) {
        this.storyText = value;
    }

    /**
     * Gets the value of the numComments property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumComments() {
        return numComments;
    }

    /**
     * Sets the value of the numComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumComments(Integer value) {
        this.numComments = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link CommentsType }
     *     
     */
    public CommentsType getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentsType }
     *     
     */
    public void setComments(CommentsType value) {
        this.comments = value;
    }

    /**
     * Gets the value of the clientResponses property.
     * 
     * @return
     *     possible object is
     *     {@link ClientResponsesType }
     *     
     */
    public ClientResponsesType getClientResponses() {
        return clientResponses;
    }

    /**
     * Sets the value of the clientResponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientResponsesType }
     *     
     */
    public void setClientResponses(ClientResponsesType value) {
        this.clientResponses = value;
    }

    /**
     * Gets the value of the additionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalFieldsType }
     *     
     */
    public AdditionalFieldsType getAdditionalFields() {
        return additionalFields;
    }

    /**
     * Sets the value of the additionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalFieldsType }
     *     
     */
    public void setAdditionalFields(AdditionalFieldsType value) {
        this.additionalFields = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link TagsType }
     *     
     */
    public TagsType getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagsType }
     *     
     */
    public void setTags(TagsType value) {
        this.tags = value;
    }

    /**
     * Gets the value of the subjectStoriesDeepLinkedUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectStoriesDeepLinkedUrl() {
        return subjectStoriesDeepLinkedUrl;
    }

    /**
     * Sets the value of the subjectStoriesDeepLinkedUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectStoriesDeepLinkedUrl(String value) {
        this.subjectStoriesDeepLinkedUrl = value;
    }

    /**
     * Gets the value of the displayLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayLocale() {
        return displayLocale;
    }

    /**
     * Sets the value of the displayLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayLocale(String value) {
        this.displayLocale = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
